#spring:
#  application:
#    name: ycode-common-fastdfs
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.31.13:8848
#
#server:
#  port: 41003
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#fastdfs.base.url: http://192.168.31.15:8888/
#storage:
#  type: fastdfs
#  fastdfs:
#    tracker_server: 192.168.31.15:22122