#spring:
#  application:
#    name: ycode-common-redis
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.31.13:8848
#
#server:
#  port: 41002
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"