version: '3.1'
services:
  ycode-common-email:
    restart: always
    image: 192.168.31.10:5000/ycode-common-email
    container_name: ycode-common-email
    hostname: ycode-common-email
    ports:
      - 41001:41001  # 外部访问端口  RESTFul端口

# 使用同一个已存在的网络  保证服务之间可以相互通信
networks:
  default:
    external:
      name: ycode