version: '3.1'
services:
  ycode-web-slideshow-admin:
    restart: always
    image: 192.168.31.10:5000/ycode-web-slideshow-admin
    container_name: ycode-web-slideshow-admin
    hostname: ycode-web-slideshow-admin
    ports:
      - 43001:43001  # 外部访问端口  RESTFul端口
      - 44001:44001  # Sentinel 熔断器 仪表盘 接收端口
# 使用同一个已存在的网络  保证服务之间可以相互通信
networks:
  default:
    external:
      name: ycode