#spring:
#  application:
#    name: ycode-web-slideshow-user
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.31.13:8848 # 服务注册与发现 地址
#    sentinel:
#      transport:
#        port: 44002
#        dashboard: 192.168.31.13:8080
#
#server:
#  port: 43002
#
#feign:
#  sentinel:
#    enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"