version: '3.1'
services:
  ycode-service-slideshow-admin:
    restart: always
    image: 192.168.31.10:5000/ycode-service-slideshow-admin
    container_name: ycode-service-slideshow-admin
    hostname: ycode-service-slideshow-admin
    ports:
      - 42001:42001  # 外部访问端口  RESTFul端口

# 使用同一个已存在的网络  保证服务之间可以相互通信
networks:
  default:
    external:
      name: ycode